(lang dune 3.6)

(name day11)

(generate_opam_files false)

(source
 (github kfl/adventofcode_2022))

(authors "Ken Friis Larsen")

(package
 (name day11)
 (depends ocaml dune))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/dune-files.html#dune-project
